import type { NextPage } from 'next'
import Head from 'next/head'
import Masthead from '../components/masthead'
import AboutUs from '../components/aboutus'
import Skills from '../components/skills'
import Works from '../components/works'
import TrustedBy from '../components/trustedby';
import ContactUs from '../components/contactus'
import Footer from '../components/footer'
import Testimonials from '../components/testimonials'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>charles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="/dist/output.css" rel="stylesheet"></link>
      </Head>
      <Masthead/>
      <AboutUs/> 
      <Skills/>
      <Works/>
      <ContactUs/>
      <Footer/>
    </div>
  )
}

export default Home
